channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.11
  - pip >=22.3.1
  - numpy ==1.23.5
  - gdal >=3.5.3
  - geopandas >=0.12.2
  - geoplot >=0.5.1
  - cleopatra >=0.2.5
  - pyramids ==0.2.11
  - loguru >=0.6.0
  - pytest >=7.2.0
  - pytest-cov ==4.0.0
